In [1]:
import pandas as pd

In [58]:
df=pd.read_csv("D:\ML Project\Sample Datasets\ICRISAT-District Level Data (2).csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\yogesh kumar\AppData\Local\Temp\ipykernel_111684\2648899271.py:1: SyntaxWarning: invalid escape sequence '\M'
  df=pd.read_csv("D:\ML Project\Sample Datasets\ICRISAT-District Level Data (2).csv")

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16047 entries, 0 to 16046
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Dist Code                            16047 non-null  int64
 1   Year                                 16047 non-null  int64
 2   State Code                           16047 non-null  int64
 3   State Name                           16047 non-null  object
 4   Dist Name                            16047 non-null  object
 5   NITROGEN CONSUMPTION (tons)          16047 non-null  float64
 6   NITROGEN SHARE IN NPK (Percent)      16047 non-null  float64
 7   NITROGEN PER HA OF NCA (Kg per ha)   16047 non-null  float64
 8   NITROGEN PER HA OF GCA (Kg per ha)   16047 non-null  float64
 9   PHOSPHATE CONSUMPTION (tons)         16047 non-null  float64
 10  PHOSPHATE SHARE IN NPK (Percent)     16047 non-null  float64
 11  PHOSPHATE PER HA OF NCA (Kg per ha)  16047 non-null  float64
 12  PHOSPHATE PER HA OF GCA (Kg per ha)  16047 non-null  float64
 13  POTASH CONSUMPTION (tons)            16047 non-null  float64
 14  POTASH SHARE IN NPK (Percent)        16047 non-null  float64
 15  POTASH PER HA OF NCA (Kg per ha)     16047 non-null  float64
 16  POTASH PER HA OF GCA (Kg per ha)     16047 non-null  float64
 17  TOTAL CONSUMPTION (tons)             16047 non-null  float64
 18  TOTAL PER HA OF NCA (Kg per ha)      16047 non-null  float64
 19  TOTAL PER HA OF GCA (Kg per ha)      16047 non-null  float64
dtypes: float64(15), int64(3), object(2)
memory usage: 2.4+ MB

In [60]:
df.head()

,Dist Code,Year,State Code,State Name,Dist Name,NITROGEN CONSUMPTION (tons),NITROGEN SHARE IN NPK (Percent),NITROGEN PER HA OF NCA (Kg per ha),NITROGEN PER HA OF GCA (Kg per ha),PHOSPHATE CONSUMPTION (tons),PHOSPHATE SHARE IN NPK (Percent),PHOSPHATE PER HA OF NCA (Kg per ha),PHOSPHATE PER HA OF GCA (Kg per ha),POTASH CONSUMPTION (tons),POTASH SHARE IN NPK (Percent),POTASH PER HA OF NCA (Kg per ha),POTASH PER HA OF GCA (Kg per ha),TOTAL CONSUMPTION (tons),TOTAL PER HA OF NCA (Kg per ha),TOTAL PER HA OF GCA (Kg per ha)
0,1,1966,14,Chhattisgarh,Durg,1375.0,80.74,1.38,1.27,292.0,17.15,0.29,0.27,36.0,2.11,0.04,0.03,1703.0,1.71,1.57
1,1,1967,14,Chhattisgarh,Durg,1516.0,78.79,1.50,1.17,207.0,10.76,0.20,0.16,201.0,10.45,0.20,0.15,1924.0,1.90,1.48
2,1,1968,14,Chhattisgarh,Durg,3042.0,85.84,2.95,2.27,458.0,12.92,0.44,0.34,44.0,1.24,0.04,0.03,3544.0,3.44,2.65
3,1,1969,14,Chhattisgarh,Durg,4131.0,82.39,3.99,3.08,847.0,16.89,0.82,0.63,36.0,0.72,0.03,0.03,5014.0,4.84,3.74
4,1,1970,14,Chhattisgarh,Durg,4594.0,67.92,4.44,3.32,2024.0,29.92,1.96,1.46,146.0,2.16,0.14,0.11,6764.0,6.54,4.89

In [56]:
# 1. Identify the columns you want by name
id_cols = ['Year', 'State Name', 'Dist Name']

# 2. Grab the last 4 columns dynamically using iloc
last_4_cols = df.columns[-4:].tolist()

# 3. Combine and filter the DataFrame
df_final = df[id_cols + last_4_cols]

# Check the result
df_final.head()

,Year,State Name,Dist Name,soil_moisture_level_percent,pesticide_usage_kg_per_hectare,altitude_meters,farming_mechanization_score
0,1966,Chhattisgarh,Durg,31.476999,2.604451,296.574626,65.062861
1,1966,Chhattisgarh,Durg,27.032150,2.999402,10.000000,34.360686
2,1966,Chhattisgarh,Durg,32.533820,1.837156,302.155906,74.779958
3,1967,Chhattisgarh,Durg,38.661209,1.635120,340.220755,67.209165
4,1967,Chhattisgarh,Durg,26.360926,1.091924,244.109476,44.357385

In [57]:
df_final.to_csv("features.csv")