In [6]:
import pandas as pd

In [7]:
df1=pd.read_csv("D:\ML Project\Sample Datasets\Custom_Crops_yield_Historical_Dataset.csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\yogesh kumar\AppData\Local\Temp\ipykernel_51912\419399030.py:1: SyntaxWarning: invalid escape sequence '\M'
  df1=pd.read_csv("D:\ML Project\Sample Datasets\Custom_Crops_yield_Historical_Dataset.csv")

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50765 entries, 0 to 50764
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Dist Code                  50765 non-null  int64
 1   Year                       50765 non-null  int64
 2   State Code                 50765 non-null  int64
 3   State Name                 50765 non-null  object
 4   Dist Name                  50765 non-null  object
 5   Crop                       50765 non-null  object
 6   Area_ha                    50765 non-null  float64
 7   Yield_kg_per_ha            50765 non-null  float64
 8   N_req_kg_per_ha            50765 non-null  float64
 9   P_req_kg_per_ha            50765 non-null  float64
 10  K_req_kg_per_ha            50765 non-null  float64
 11  Total_N_kg                 50765 non-null  float64
 12  Total_P_kg                 50765 non-null  float64
 13  Total_K_kg                 50765 non-null  float64
 14  Temperature_C              50765 non-null  int64
 15  Humidity_%                 50765 non-null  int64
 16  pH                         50765 non-null  float64
 17  Rainfall_mm                50765 non-null  int64
 18  Wind_Speed_m_s             50765 non-null  float64
 19  Solar_Radiation_MJ_m2_day  50765 non-null  int64
dtypes: float64(10), int64(7), object(3)
memory usage: 7.7+ MB

In [9]:
df1.sample(10)

,Dist Code,Year,State Code,State Name,Dist Name,Crop,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Total_N_kg,Total_P_kg,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day
39740,242,2008,16,Uttarakhand,Tehri Garhwal,maize,2040.0,1024.51,27.66177,12.29412,17.41667,5.643001e+04,2.508000e+04,3.553001e+04,22,70,6.0,800,2.5,20
13437,76,1979,5,Karnataka,Bijapur / Vijayapura,maize,28000.0,2707.14,73.09278,32.48568,46.02138,2.046598e+06,9.095990e+05,1.288599e+06,22,70,6.0,800,2.5,20
35242,210,1992,12,Uttar Pradesh,Allahabad,chickpea,53440.0,1072.79,19.31022,10.72790,19.31022,1.031938e+06,5.732990e+05,1.031938e+06,20,60,6.5,600,1.5,16
18406,106,2013,7,Maharashtra,Solapur,maize,44300.0,2209.93,59.66811,26.51916,37.56881,2.643297e+06,1.174799e+06,1.664298e+06,22,70,6.0,800,2.5,20
23481,134,1978,3,Gujarat,Panchmahal,chickpea,30000.0,1200.00,21.60000,12.00000,21.60000,6.480000e+05,3.600000e+05,6.480000e+05,20,60,6.5,600,1.5,16
28463,164,2015,10,Rajasthan,Udaipur,cotton,5830.0,80.04,2.16108,0.96048,2.16108,1.259910e+04,5.599598e+03,1.259910e+04,28,65,6.0,700,3.0,22
21737,124,1971,3,Gujarat,Bharuch,cotton,272700.0,193.99,5.23773,2.32788,5.23773,1.428329e+06,6.348129e+05,1.428329e+06,28,65,6.0,700,3.0,22
19885,114,1978,7,Maharashtra,Akola,rice,8100.0,1320.99,33.02475,15.85188,29.06178,2.675005e+05,1.284002e+05,2.354004e+05,25,80,6.5,1200,2.0,18
21924,125,1966,3,Gujarat,Vadodara / Baroda,cotton,247000.0,190.28,5.13756,2.28336,5.13756,1.268977e+06,5.639899e+05,1.268977e+06,28,65,6.0,700,3.0,22
5446,34,1977,6,Madhya Pradesh,Jhabua,chickpea,25500.0,513.73,9.24714,5.13730,9.24714,2.358021e+05,1.310011e+05,2.358021e+05,20,60,6.5,600,1.5,16

In [10]:
df1=df1.drop(columns=['Dist Code', 'State Code'])

In [11]:
df1.sample(10)

,Year,State Name,Dist Name,Crop,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Total_N_kg,Total_P_kg,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day
27676,1979,Rajasthan,Swami Madhopur,maize,6000.0,466.67,12.60009,5.60004,7.93339,7.560054e+04,3.360024e+04,4.760034e+04,22,70,6.0,800,2.5,20
33482,1982,Uttar Pradesh,Bareilly,chickpea,13100.0,793.89,14.29002,7.93890,14.29002,1.871993e+05,1.039996e+05,1.871993e+05,20,60,6.5,600,1.5,16
39052,1990,Uttar Pradesh,Barabanki,rice,171620.0,1776.48,44.41200,21.31776,39.08256,7.621987e+06,3.658554e+06,6.707349e+06,25,80,6.5,1200,2.0,18
13281,1992,Karnataka,Belgaum,rice,64430.0,1723.58,43.08950,20.68296,37.91876,2.776256e+06,1.332603e+06,2.443106e+06,25,80,6.5,1200,2.0,18
34952,2000,Uttar Pradesh,Kanpur,rice,79780.0,1753.82,43.84550,21.04584,38.58404,3.497994e+06,1.679037e+06,3.078235e+06,25,80,6.5,1200,2.0,18
1159,1973,Madhya Pradesh,Balaghat,maize,4500.0,977.78,26.40006,11.73336,16.62226,1.188003e+05,5.280012e+04,7.480017e+04,22,70,6.0,800,2.5,20
41340,1987,Assam,North Cachar Hil / Dima hasao,rice,12680.0,996.06,24.90150,11.95272,21.91332,3.157510e+05,1.515605e+05,2.778609e+05,25,80,6.5,1200,2.0,18
17084,1989,Maharashtra,Dhule,chickpea,25400.0,535.43,9.63774,5.35430,9.63774,2.447986e+05,1.359992e+05,2.447986e+05,20,60,6.5,600,1.5,16
19800,2005,Maharashtra,Buldhana,maize,33900.0,1676.70,45.27090,20.12040,28.50390,1.534684e+06,6.820816e+05,9.662822e+05,22,70,6.0,800,2.5,20
50655,1977,Jharkhand,Singhbhum,maize,11020.0,734.12,19.82124,8.80944,12.48004,2.184301e+05,9.708003e+04,1.375300e+05,22,70,6.0,800,2.5,20

In [12]:
df1.head(30)

,Year,State Name,Dist Name,Crop,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Total_N_kg,Total_P_kg,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day
0,1966,Chhattisgarh,Durg,rice,548000.0,337.59,8.43975,4.05108,7.42698,4.624983e+06,2219991.840,4.069985e+06,25,80,6.5,1200,2.0,18
1,1966,Chhattisgarh,Durg,maize,3000.0,666.67,18.00009,8.00004,11.33339,5.400027e+04,24000.120,3.400017e+04,22,70,6.0,800,2.5,20
2,1966,Chhattisgarh,Durg,chickpea,54000.0,500.00,9.00000,5.00000,9.00000,4.860000e+05,270000.000,4.860000e+05,20,60,6.5,600,1.5,16
3,1967,Chhattisgarh,Durg,rice,547000.0,747.71,18.69275,8.97252,16.44962,1.022493e+07,4907968.440,8.997942e+06,25,80,6.5,1200,2.0,18
4,1967,Chhattisgarh,Durg,maize,3000.0,1000.00,27.00000,12.00000,17.00000,8.100000e+04,36000.000,5.100000e+04,22,70,6.0,800,2.5,20
5,1967,Chhattisgarh,Durg,chickpea,52000.0,288.46,5.19228,2.88460,5.19228,2.699986e+05,149999.200,2.699986e+05,20,60,6.5,600,1.5,16
6,1968,Chhattisgarh,Durg,rice,556300.0,841.27,21.03175,10.09524,18.50794,1.169996e+07,5615982.012,1.029597e+07,25,80,6.5,1200,2.0,18
7,1968,Chhattisgarh,Durg,maize,2800.0,714.29,19.28583,8.57148,12.14293,5.400032e+04,24000.144,3.400020e+04,22,70,6.0,800,2.5,20
8,1968,Chhattisgarh,Durg,chickpea,51300.0,448.34,8.07012,4.48340,8.07012,4.139972e+05,229998.420,4.139972e+05,20,60,6.5,600,1.5,16
9,1969,Chhattisgarh,Durg,rice,563400.0,711.40,17.78500,8.53680,15.65080,1.002007e+07,4809633.120,8.817661e+06,25,80,6.5,1200,2.0,18
10,1969,Chhattisgarh,Durg,maize,2700.0,851.85,22.99995,10.22220,14.48145,6.209986e+04,27599.940,3.909992e+04,22,70,6.0,800,2.5,20
11,1969,Chhattisgarh,Durg,chickpea,52600.0,439.16,7.90488,4.39160,7.90488,4.157967e+05,230998.160,4.157967e+05,20,60,6.5,600,1.5,16
12,1970,Chhattisgarh,Durg,rice,571600.0,828.55,20.71375,9.94260,18.22810,1.183998e+07,5683190.160,1.041918e+07,25,80,6.5,1200,2.0,18
13,1970,Chhattisgarh,Durg,maize,2500.0,1320.00,35.64000,15.84000,22.44000,8.910000e+04,39600.000,5.610000e+04,22,70,6.0,800,2.5,20
14,1970,Chhattisgarh,Durg,chickpea,53300.0,611.63,11.00934,6.11630,11.00934,5.867978e+05,325998.790,5.867978e+05,20,60,6.5,600,1.5,16
15,1971,Chhattisgarh,Durg,rice,581800.0,709.69,17.74225,8.51628,15.61318,1.032244e+07,4954771.704,9.083748e+06,25,80,6.5,1200,2.0,18
16,1971,Chhattisgarh,Durg,maize,2700.0,1148.15,31.00005,13.77780,19.51855,8.370014e+04,37200.060,5.270009e+04,22,70,6.0,800,2.5,20
17,1971,Chhattisgarh,Durg,chickpea,50300.0,652.09,11.73762,6.52090,11.73762,5.904023e+05,328001.270,5.904023e+05,20,60,6.5,600,1.5,16
18,1972,Chhattisgarh,Durg,rice,582200.0,654.41,16.36025,7.85292,14.39702,9.524938e+06,4571970.024,8.381945e+06,25,80,6.5,1200,2.0,18
19,1972,Chhattisgarh,Durg,maize,2800.0,1142.86,30.85722,13.71432,19.42862,8.640022e+04,38400.096,5.440014e+04,22,70,6.0,800,2.5,20
20,1972,Chhattisgarh,Durg,chickpea,52300.0,623.33,11.21994,6.23330,11.21994,5.868029e+05,326001.590,5.868029e+05,20,60,6.5,600,1.5,16
21,1973,Chhattisgarh,Durg,rice,600000.0,786.50,19.66250,9.43800,17.30300,1.179750e+07,5662800.000,1.038180e+07,25,80,6.5,1200,2.0,18
22,1973,Chhattisgarh,Durg,maize,2900.0,931.03,25.13781,11.17236,15.82751,7.289965e+04,32399.844,4.589978e+04,22,70,6.0,800,2.5,20
23,1973,Chhattisgarh,Durg,chickpea,56400.0,574.47,10.34046,5.74470,10.34046,5.832019e+05,324001.080,5.832019e+05,20,60,6.5,600,1.5,16
24,1974,Chhattisgarh,Durg,rice,587400.0,372.83,9.32075,4.47396,8.20226,5.475009e+06,2628004.104,4.818008e+06,25,80,6.5,1200,2.0,18
25,1974,Chhattisgarh,Durg,maize,2900.0,1000.00,27.00000,12.00000,17.00000,7.830000e+04,34800.000,4.930000e+04,22,70,6.0,800,2.5,20
26,1974,Chhattisgarh,Durg,chickpea,54900.0,746.81,13.44258,7.46810,13.44258,7.379976e+05,409998.690,7.379976e+05,20,60,6.5,600,1.5,16
27,1975,Chhattisgarh,Durg,rice,598300.0,758.82,18.97050,9.10584,16.69404,1.135005e+07,5448024.072,9.988044e+06,25,80,6.5,1200,2.0,18
28,1975,Chhattisgarh,Durg,maize,2900.0,1000.00,27.00000,12.00000,17.00000,7.830000e+04,34800.000,4.930000e+04,22,70,6.0,800,2.5,20
29,1975,Chhattisgarh,Durg,chickpea,58300.0,518.01,9.32418,5.18010,9.32418,5.435997e+05,301999.830,5.435997e+05,20,60,6.5,600,1.5,16

In [13]:
df1 = df1.groupby(['Year', 'State Name', 'Dist Name'], as_index=False).mean(numeric_only=True)

In [14]:
df1.head(30)

,Year,State Name,Dist Name,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Total_N_kg,Total_P_kg,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day
0,1966,Andhra Pradesh,Ananthapur,27000.000000,644.445000,15.409935,7.483340,13.362315,7.012758e+05,3.364004e+05,6.187757e+05,23.750000,68.75,6.250000,825.000000,2.25,19.0
1,1966,Andhra Pradesh,Chittoor,78050.000000,1323.720000,34.093000,15.884640,26.621840,3.213858e+06,1.542604e+06,2.827857e+06,23.500000,75.00,6.250000,1000.000000,2.25,19.0
2,1966,Andhra Pradesh,East Godavari,108666.666667,951.853333,23.763000,11.222240,18.874107,4.210812e+06,2.021006e+06,3.703477e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
3,1966,Andhra Pradesh,Guntur,72500.000000,696.097500,17.500653,8.228170,13.903432,2.493495e+06,1.196498e+06,2.192246e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
4,1966,Andhra Pradesh,Kadapa YSR,22525.000000,728.950000,18.240415,8.597400,14.591062,7.462759e+05,3.580505e+05,6.575258e+05,23.750000,68.75,6.250000,825.000000,2.25,19.0
5,1966,Andhra Pradesh,Krishna,95000.000000,641.715000,16.232875,7.600580,12.767730,3.010342e+06,1.444696e+06,2.647843e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
6,1966,Andhra Pradesh,Kurnool,61300.000000,662.287500,16.509320,7.780785,13.075645,8.403493e+05,4.015997e+05,7.483491e+05,23.750000,68.75,6.250000,825.000000,2.25,19.0
7,1966,Andhra Pradesh,S.P.S. Nellore,64375.000000,545.752500,13.340485,6.382365,11.123225,2.034396e+06,9.764481e+05,1.790396e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
8,1966,Andhra Pradesh,Srikakulam,140000.000000,905.020000,23.625500,10.860240,17.410440,2.838514e+06,1.362007e+06,2.494513e+06,23.500000,75.00,6.250000,1000.000000,2.25,19.0
9,1966,Andhra Pradesh,Visakhapatnam,51500.000000,432.893333,10.689000,5.061387,8.423653,7.679280e+05,3.683308e+05,6.735953e+05,22.333333,70.00,6.333333,866.666667,2.00,18.0
10,1966,Andhra Pradesh,West Godavari,119200.000000,964.753333,23.452167,11.243707,19.307907,4.894974e+06,2.349537e+06,4.306973e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
11,1966,Assam,Cachar,49577.500000,573.505000,13.695588,6.609335,11.602910,1.391233e+06,6.677980e+05,1.224241e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
12,1966,Assam,Darrang,57655.000000,502.422500,12.216388,5.833420,9.942070,1.346594e+06,6.461822e+05,1.183572e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
13,1966,Assam,Goalpara,81900.000000,445.760000,10.616333,5.116725,8.806218,1.525898e+06,7.324662e+05,1.342452e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
14,1966,Assam,Kamrup,103382.500000,497.060000,11.667768,5.649335,9.626938,1.722656e+06,8.268630e+05,1.515144e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
15,1966,Assam,Karbi Anglong,13990.000000,628.600000,14.930660,7.230700,12.604275,3.818396e+05,1.827648e+05,3.334021e+05,23.750000,68.75,6.250000,825.000000,2.25,19.0
16,1966,Assam,Lakhimpur,99835.000000,761.130000,19.526480,9.133560,15.499285,2.538661e+06,1.217880e+06,2.229256e+06,23.500000,75.00,6.250000,1000.000000,2.25,19.0
17,1966,Assam,Nagaon,50632.500000,524.267500,12.385095,5.995755,10.474225,1.113957e+06,5.347173e+05,9.801917e+05,23.750000,68.75,6.250000,825.000000,2.25,19.0
18,1966,Assam,Sibsagar,60615.000000,528.000000,12.637500,6.086000,10.647250,1.494780e+06,7.174784e+05,1.315301e+06,23.750000,68.75,6.250000,825.000000,2.25,19.0
19,1966,Bihar,Bhagalpur,76983.333333,627.920000,15.450027,7.236120,11.220783,9.950332e+05,4.595681e+05,7.232023e+05,22.333333,70.00,6.333333,866.666667,2.00,18.0
20,1966,Bihar,Champaran,143780.000000,522.313333,12.341620,5.937240,9.728337,1.555850e+06,7.415737e+05,1.322128e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
21,1966,Bihar,Darbhanga,138880.000000,651.340000,15.916817,7.488940,11.729433,1.595576e+06,7.432914e+05,1.226133e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
22,1966,Bihar,Gaya,127463.333333,504.576667,12.385527,5.819993,9.147450,9.561141e+05,4.581334e+05,8.144024e+05,22.333333,70.00,6.333333,866.666667,2.00,18.0
23,1966,Bihar,Mungair,107126.666667,711.316667,18.135373,8.389980,13.200260,2.597087e+06,1.181143e+06,1.803658e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
24,1966,Bihar,Muzaffarpur,130576.666667,546.803333,13.366387,6.282953,9.793033,1.295521e+06,5.976839e+05,9.598004e+05,22.333333,70.00,6.333333,866.666667,2.00,18.0
25,1966,Bihar,Patna,66123.333333,587.140000,13.827327,6.612867,10.392270,5.245182e+05,2.501623e+05,4.048741e+05,22.333333,70.00,6.333333,866.666667,2.00,18.0
26,1966,Bihar,Purnea,156473.333333,640.086667,15.891610,7.426593,11.622997,1.761204e+06,8.313757e+05,1.436945e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
27,1966,Bihar,Saharsa,60256.666667,466.823333,11.459157,5.395467,8.579737,7.041935e+05,3.256252e+05,5.306308e+05,22.333333,70.00,6.333333,866.666667,2.00,18.0
28,1966,Bihar,Saran,104376.666667,650.883333,15.950070,7.470053,11.463590,1.657809e+06,7.509243e+05,1.116980e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0
29,1966,Bihar,Shahabad (now part of Bhojpur district),179656.666667,490.330000,11.870377,5.644747,9.185400,1.881363e+06,9.131897e+05,1.652606e+06,22.333333,70.00,6.333333,866.666667,2.00,18.0

In [15]:
df1.describe()

,Year,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Total_N_kg,Total_P_kg,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day
count,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,1.597200e+04,1.597200e+04,1.597200e+04,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000
mean,1991.659216,64995.435136,1204.539305,29.682653,14.059965,23.694151,2.342014e+06,1.119942e+06,2.009119e+06,23.244689,69.881929,6.295481,862.303823,2.138200,18.552801
std,14.963793,55235.023521,661.368072,16.801349,7.846941,13.164703,2.821599e+06,1.346741e+06,2.449945e+06,0.952985,2.975855,0.077366,93.980100,0.164852,0.659407
min,1966.000000,10.000000,8.000000,0.144000,0.080000,0.144000,4.589460e+01,2.039760e+01,4.589460e+01,20.000000,60.000000,6.000000,600.000000,1.500000,16.000000
25%,1979.000000,26148.750000,754.305000,18.156863,8.685064,14.575228,5.219622e+05,2.548383e+05,4.462070e+05,22.333333,68.750000,6.250000,825.000000,2.000000,18.000000
50%,1992.000000,50435.000000,1063.396667,25.894619,12.328755,20.772745,1.364905e+06,6.533315e+05,1.150709e+06,23.750000,70.000000,6.250000,866.666667,2.250000,19.000000
75%,2005.000000,87335.416667,1503.188125,37.181250,17.609777,29.761049,3.110209e+06,1.486441e+06,2.674485e+06,23.750000,70.000000,6.333333,866.666667,2.250000,19.000000
max,2017.000000,553755.000000,20280.966667,372.292307,204.462507,364.738163,3.679793e+07,1.766151e+07,3.237160e+07,28.000000,80.000000,6.500000,1200.000000,3.000000,22.000000

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15972 entries, 0 to 15971
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       15972 non-null  int64
 1   State Name                 15972 non-null  object
 2   Dist Name                  15972 non-null  object
 3   Area_ha                    15972 non-null  float64
 4   Yield_kg_per_ha            15972 non-null  float64
 5   N_req_kg_per_ha            15972 non-null  float64
 6   P_req_kg_per_ha            15972 non-null  float64
 7   K_req_kg_per_ha            15972 non-null  float64
 8   Total_N_kg                 15972 non-null  float64
 9   Total_P_kg                 15972 non-null  float64
 10  Total_K_kg                 15972 non-null  float64
 11  Temperature_C              15972 non-null  float64
 12  Humidity_%                 15972 non-null  float64
 13  pH                         15972 non-null  float64
 14  Rainfall_mm                15972 non-null  float64
 15  Wind_Speed_m_s             15972 non-null  float64
 16  Solar_Radiation_MJ_m2_day  15972 non-null  float64
dtypes: float64(14), int64(1), object(2)
memory usage: 2.1+ MB

In [17]:
df1.columns.to_list()

['Year',
 'State Name',
 'Dist Name',
 'Area_ha',
 'Yield_kg_per_ha',
 'N_req_kg_per_ha',
 'P_req_kg_per_ha',
 'K_req_kg_per_ha',
 'Total_N_kg',
 'Total_P_kg',
 'Total_K_kg',
 'Temperature_C',
 'Humidity_%',
 'pH',
 'Rainfall_mm',
 'Wind_Speed_m_s',
 'Solar_Radiation_MJ_m2_day']

In [18]:
df1.to_csv("features2.csv")